######################################################################
# Automatically generated by qmake (3.0) sob. lip 4 12:38:35 2015
######################################################################

TEMPLATE = app
TARGET = test
INCLUDEPATH += . ../

QT += gui widgets

CONFIG += c++11 console

LIBS += -ldl

HEADERS += widget.h
SOURCES += main.cpp widget.cpp ../cuwrap.cpp

DISTFILES += \
    kernel.cu
