version: "3"
services:
    generate_enum_utils:
        build: .
        volumes: 
            - ../input:/var/opt/castxml/input/:ro
            - ../output:/var/opt/castxml/output/:wo
            - ../scripts:/var/opt/castxml/scripts:ro
        entrypoint: /var/opt/castxml/scripts/call_generate_enum_utils.sh
