/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Test */

#ifndef _Included_Test
#define _Included_Test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Test
 * Method:    create_image
 * Signature: (III[BI)J
 */
JNIEXPORT jlong JNICALL Java_Test_create_1image
  (JNIEnv *, jclass, jint, jint, jint, jbyteArray, jint);

/*
 * Class:     Test
 * Method:    create_frame
 * Signature: (JJ)LFrame;
 */
JNIEXPORT jobject JNICALL Java_Test_create_1frame
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     Test
 * Method:    get_frame_size
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Test_get_1frame_1size
  (JNIEnv *, jclass);

/*
 * Class:     Test
 * Method:    create_frame_raw
 * Signature: (JJ[B)V
 */
JNIEXPORT void JNICALL Java_Test_create_1frame_1raw
  (JNIEnv *, jclass, jlong, jlong, jbyteArray);

/*
 * Class:     Test
 * Method:    get_content_raw
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_Test_get_1content_1raw
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     Test
 * Method:    get_index_raw
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_Test_get_1index_1raw
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     Test
 * Method:    free_frame_raw
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_Test_free_1frame_1raw
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     Test
 * Method:    create_frame_and_image
 * Signature: (JII)LFrame;
 */
JNIEXPORT jobject JNICALL Java_Test_create_1frame_1and_1image
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     Test
 * Method:    get_content
 * Signature: (LFrame;)J
 */
JNIEXPORT jlong JNICALL Java_Test_get_1content
  (JNIEnv *, jclass, jobject);

/*
 * Class:     Test
 * Method:    get_index
 * Signature: (LFrame;)J
 */
JNIEXPORT jlong JNICALL Java_Test_get_1index
  (JNIEnv *, jclass, jobject);

/*
 * Class:     Test
 * Method:    get_width
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_Test_get_1width
  (JNIEnv *, jclass, jlong);

/*
 * Class:     Test
 * Method:    get_height
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_Test_get_1height
  (JNIEnv *, jclass, jlong);

/*
 * Class:     Test
 * Method:    get_stride
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_Test_get_1stride
  (JNIEnv *, jclass, jlong);

/*
 * Class:     Test
 * Method:    get_data
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_Test_get_1data
  (JNIEnv *, jclass, jlong);

/*
 * Class:     Test
 * Method:    free_frame
 * Signature: (LFrame;)V
 */
JNIEXPORT void JNICALL Java_Test_free_1frame
  (JNIEnv *, jclass, jobject);

/*
 * Class:     Test
 * Method:    free_image
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_Test_free_1image
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
