######################################################################
# Automatically generated by qmake (3.0) sön maj 15 20:11:14 2016
######################################################################

TEMPLATE = app
TARGET = dvz
INCLUDEPATH += .

QMAKE_CC=gcc

CONFIG -= qt

QMAKE_CFLAGS += -std=c99

# Input
HEADERS += dvz_context.h dvz_renderer.h
SOURCES += dvz_context.c dvz_renderer.c main.c
